# Generated by Django 4.2.27 on 2025-12-08 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_alter_warehouse_type'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseIncomeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MoneyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('currency', models.CharField(default='RUB', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='MoneyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tran_type', models.CharField(choices=[('income', 'Приход'), ('expense', 'Расход'), ('transfer', 'Перемещение')], help_text='Тип операции: приход / расход / перемещение', max_length=20)),
                ('date', models.DateField(help_text='Дата операции (когда реально прошёл платёж)')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Сумма операции в валюте операции', max_digits=12)),
                ('currency', models.CharField(default='RUB', help_text='Валюта операции: RUB, KGS и т.п.', max_length=3)),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=1, help_text='Курс к рублю, если операция не в рублях (для пересчёта в отчёты)', max_digits=10)),
                ('comment', models.CharField(blank=True, help_text='Любой комментарий: номер счёта, платёжки и т.п.', max_length=255)),
                ('account_from', models.ForeignKey(blank=True, help_text='Счёт, с которого списываются деньги (для расхода/перемещения)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transactions', to='finance.moneyaccount')),
                ('account_to', models.ForeignKey(blank=True, help_text='Счёт, на который приходят деньги (для прихода/перемещения)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transactions', to='finance.moneyaccount')),
                ('category', models.ForeignKey(blank=True, help_text='Статья движения денег (для аналитики)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='money_transactions', to='finance.expenseincomecategory')),
                ('counterparty', models.ForeignKey(blank=True, help_text='Контрагент (фабрика, карго, фулфилмент, WB), к которому относится операция', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='money_transactions', to='catalog.counterparty')),
                ('order', models.ForeignKey(blank=True, help_text='Заказ поставщику, к которому относится платёж (если есть)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='money_transactions', to='orders.purchaseorder')),
            ],
        ),
    ]
