# Generated by Django 4.2.27 on 2025-12-14 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('WB_STOCKS_EXCEL', 'WB Stocks Excel'), ('WB_REPORT_EXCEL', 'WB Report Excel'), ('WB_API', 'WB API')], max_length=20)),
                ('original_filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='wb_imports/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('PARSED', 'Parsed'), ('APPLIED', 'Applied'), ('ERROR', 'Error')], default='UPLOADED', max_length=20)),
                ('error_log', models.TextField(blank=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wb_import_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='WBProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm_id', models.BigIntegerField(db_index=True, unique=True)),
                ('vendor_code', models.CharField(db_index=True, max_length=255)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('brand', models.CharField(blank=True, max_length=255)),
                ('subject', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['vendor_code'],
                'indexes': [models.Index(fields=['vendor_code'], name='wb_wbproduc_vendor__3ae44e_idx')],
            },
        ),
        migrations.CreateModel(
            name='WBStockSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loaded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('warehouse_name', models.CharField(blank=True, max_length=255)),
                ('nm_id', models.BigIntegerField(db_index=True)),
                ('vendor_code', models.CharField(blank=True, db_index=True, max_length=255)),
                ('barcode', models.CharField(db_index=True, max_length=255)),
                ('tech_size', models.CharField(blank=True, max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('in_way_to_client', models.IntegerField(default=0)),
                ('in_way_from_client', models.IntegerField(default=0)),
                ('quantity_full', models.IntegerField(default=0)),
                ('import_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_snapshots', to='wb.importfile')),
            ],
            options={
                'ordering': ['-loaded_at', 'vendor_code', 'barcode'],
                'indexes': [models.Index(fields=['loaded_at'], name='wb_wbstocks_loaded__6fcb7a_idx'), models.Index(fields=['nm_id', 'barcode'], name='wb_wbstocks_nm_id_ce906f_idx'), models.Index(fields=['vendor_code'], name='wb_wbstocks_vendor__e30b6c_idx')],
            },
        ),
        migrations.CreateModel(
            name='WBBarcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech_size', models.CharField(blank=True, max_length=100)),
                ('barcode', models.CharField(db_index=True, max_length=255, unique=True)),
                ('wb_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcodes', to='wb.wbproduct')),
            ],
            options={
                'ordering': ['wb_product', 'barcode'],
                'indexes': [models.Index(fields=['barcode'], name='wb_wbbarcod_barcode_8cd5bc_idx')],
            },
        ),
        migrations.CreateModel(
            name='ImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField()),
                ('raw_json', models.JSONField()),
                ('errors', models.JSONField(blank=True, null=True)),
                ('import_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='wb.importfile')),
            ],
            options={
                'ordering': ['import_file', 'row_number'],
                'indexes': [models.Index(fields=['import_file', 'row_number'], name='wb_importro_import__8628f7_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='importfile',
            index=models.Index(fields=['status', 'uploaded_at'], name='wb_importfi_status_b3ecb3_idx'),
        ),
    ]
