# Generated by Django 4.2.27 on 2025-12-08 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_alter_warehouse_type'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('income', 'Приход'), ('outcome', 'Расход'), ('transfer', 'Перемещение'), ('writeoff', 'Списание'), ('inventory', 'Инвентаризация')], help_text='Тип движения: приход/расход/перемещение/списание/инвентаризация', max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True, help_text='Когда было зафиксировано движение')),
                ('comment', models.CharField(blank=True, help_text='Произвольный комментарий к документу движения', max_length=255)),
                ('related_supply', models.ForeignKey(blank=True, help_text='Если движение связано с конкретной поставкой', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='orders.supply')),
                ('warehouse_from', models.ForeignKey(blank=True, help_text='Склад-источник (может быть пустым для прихода)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_movements', to='catalog.warehouse')),
                ('warehouse_to', models.ForeignKey(blank=True, help_text='Склад-получатель (может быть пустым для расхода)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_movements', to='catalog.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='StockMovementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Количество единиц в этом движении')),
                ('batch', models.ForeignKey(help_text='Партия товара, к которой относится движение', on_delete=django.db.models.deletion.PROTECT, related_name='stock_items', to='orders.productbatch')),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouse.stockmovement')),
            ],
        ),
    ]
