# Generated by Django 4.2.27 on 2025-12-12 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_alter_warehouse_type'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumablePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Дата закупки расходников')),
                ('currency', models.CharField(default='RUB', help_text='Валюта закупки: RUB, KGS и т.п.', max_length=3)),
                ('supplier', models.ForeignKey(help_text='Поставщик расходников', limit_choices_to={'type': 'factory'}, on_delete=django.db.models.deletion.PROTECT, related_name='consumable_purchases', to='catalog.counterparty')),
            ],
        ),
        migrations.CreateModel(
            name='TechCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Условное название техкарты (например, 'Блузка Малори базовая')", max_length=200)),
                ('batch', models.OneToOneField(help_text='Партия изделий, для которой действует техкарта', on_delete=django.db.models.deletion.PROTECT, related_name='tech_card', to='orders.productbatch')),
            ],
        ),
        migrations.CreateModel(
            name='TechCardItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_per_unit', models.DecimalField(decimal_places=3, help_text='Норма расхода на 1 изделие (в тех же единицах, что и расходник)', max_digits=12)),
                ('consumable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='techcard_items', to='catalog.consumable')),
                ('techcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='production.techcard')),
            ],
        ),
        migrations.CreateModel(
            name='ConsumablePurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Количество (м/шт/кг) по документу', max_digits=12)),
                ('amount_rub', models.DecimalField(decimal_places=2, help_text='Сумма в рублях (полная сумма строки)', max_digits=12)),
                ('unit_price_rub', models.DecimalField(decimal_places=4, help_text='Цена за 1 единицу в рублях', max_digits=12)),
                ('consumable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='catalog.consumable')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='production.consumablepurchase')),
            ],
        ),
    ]
