# Generated by Django 4.2.27 on 2025-12-12 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_warehouse_type'),
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumableStockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('income', 'Приход'), ('transfer', 'Перемещение'), ('writeoff', 'Списание')], help_text='Тип движения расходников', max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True, help_text='Когда зафиксировано движение')),
                ('comment', models.CharField(blank=True, help_text='Комментарий к движению (номер накладной, причина и т.п.)', max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='consumablepurchase',
            name='supplier',
            field=models.ForeignKey(help_text='Поставщик расходников', on_delete=django.db.models.deletion.PROTECT, related_name='consumable_purchases', to='catalog.counterparty'),
        ),
        migrations.AlterField(
            model_name='techcard',
            name='name',
            field=models.CharField(help_text="Название техкарты (например, 'Блузка Малори базовая')", max_length=200),
        ),
        migrations.AlterField(
            model_name='techcarditem',
            name='quantity_per_unit',
            field=models.DecimalField(decimal_places=3, help_text='Норма расхода на 1 изделие (в тех же единицах, что расходник)', max_digits=12),
        ),
        migrations.CreateModel(
            name='ConsumableStockMovementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Количество расходника в этом движении', max_digits=12)),
                ('unit_cost_rub', models.DecimalField(decimal_places=4, help_text='Учётная цена за единицу на момент движения', max_digits=12)),
                ('consumable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_items', to='catalog.consumable')),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='production.consumablestockmovement')),
            ],
        ),
        migrations.AddField(
            model_name='consumablestockmovement',
            name='related_purchase',
            field=models.ForeignKey(blank=True, help_text='Закупка, из которой пришли расходники (для прихода)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='production.consumablepurchase'),
        ),
        migrations.AddField(
            model_name='consumablestockmovement',
            name='warehouse_from',
            field=models.ForeignKey(blank=True, help_text='Склад-источник (для списаний/перемещений)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consumable_out_movements', to='catalog.warehouse'),
        ),
        migrations.AddField(
            model_name='consumablestockmovement',
            name='warehouse_to',
            field=models.ForeignKey(blank=True, help_text='Склад-получатель (для приходов/перемещений)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consumable_in_movements', to='catalog.warehouse'),
        ),
    ]
