# Generated by Django 4.2.27 on 2025-12-14 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_warehouse_type'),
        ('production', '0002_consumablestockmovement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techcard',
            name='batch',
        ),
        migrations.AddField(
            model_name='techcard',
            name='is_default',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='techcard',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Товар, для которого действует техкарта', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tech_cards', to='catalog.product'),
        ),
        migrations.AlterField(
            model_name='techcard',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='techcarditem',
            name='quantity_per_unit',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
        migrations.AddConstraint(
            model_name='techcard',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('product',), name='uniq_default_techcard_per_product'),
        ),
    ]
