# Generated by Django 4.2.27 on 2025-12-14 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_warehouse_type'),
        ('production', '0003_remove_techcard_batch_techcard_is_default_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techcard',
            name='product',
            field=models.ForeignKey(help_text='Товар, для которого действует техкарта', on_delete=django.db.models.deletion.PROTECT, related_name='tech_cards', to='catalog.product'),
        ),
    ]
