# Generated by Django 4.2.27 on 2025-12-08 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='type',
            field=models.CharField(choices=[('production', 'Производство'), ('ff', 'Фулфилмент'), ('cargo', 'Карго / Транзит'), ('mp_warehouse', 'Склад маркетплейса'), ('own', 'Собственный склад'), ('other', 'Другое')], default='other', max_length=20),
        ),
    ]
