# Generated by Django 4.2.27 on 2025-12-07 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=50)),
                ('size', models.CharField(blank=True, max_length=20)),
                ('quantity_planned', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField()),
                ('currency', models.CharField(default='RUB', help_text='Код валюты, например RUB или KGS', max_length=3)),
                ('status', models.CharField(default='draft', help_text='Статус заказa: draft / in_progress / closed', max_length=20)),
                ('total_amount_currency', models.DecimalField(decimal_places=2, default=0, help_text='Сумма заказа в валюте (из строк заказа)', max_digits=12)),
                ('total_amount_rub', models.DecimalField(decimal_places=2, default=0, help_text='Сумма заказа в рублях', max_digits=12)),
                ('factory', models.ForeignKey(limit_choices_to={'type': 'factory'}, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='catalog.counterparty')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('status', models.CharField(default='in_transit', help_text='in_transit / arrived / accepted', max_length=20)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplies', to='orders.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='SupplyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supply_items', to='orders.productbatch')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.supply')),
                ('warehouse_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_supply_items', to='catalog.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price_currency', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_currency', models.DecimalField(decimal_places=2, max_digits=12)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='orders.productbatch')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.purchaseorder')),
            ],
        ),
        migrations.AddField(
            model_name='productbatch',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='orders.purchaseorder'),
        ),
        migrations.AddField(
            model_name='productbatch',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='catalog.product'),
        ),
    ]
