# Generated by Django 4.2.27 on 2025-12-14 20:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbatch',
            name='material_cost_per_unit',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12),
        ),
        migrations.AddField(
            model_name='productbatch',
            name='material_cost_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
